### ISSUE TITLE
ALM does not work with GIT on Windows

### ISSUE THREAD

**Issue by hoegge** [alm-tools/alm#570] opened 2017-07-23 13:53 UTC
Running a command like "git add all" gives result:

```
{ "addResult": "", "commitResult": 
"[master 5a9d5f7] test commit\n 1 file changed, 2 insertions(+), 5 deletions(-)\n", 
"pushResult": "fatal: 'origin' does not appear to be a git repository\nfatal: 
Could not read from remote repository.\n\nPlease make sure 
you have the correct access rights\nand the repository exists.\n" }
```

which is a bit strange when the commit works ok.
Also the git status gutter color bars on the left indicating changes are not shown as in documentation.

My git works fine from the command line and the repository is ok without having to run as administrator so rights should be ok.

kr
Morten

**Comment by basarat** [comment] 2017-07-23 20:49
`fatal: 'origin' does not appear to be a git repository`

This is a git error. Check git installation. If commands dont work on commnad line, they will not work in alm. Try cloning your project again :rose:

**Comment by hoegge** [comment] 2017-07-23 21:06
@basarat: As I already wrote, GIT works perfect on the same repository from the command line and from Visual Studio

**Comment by basarat** [comment] 2017-07-24 01:11
Can you run these commands manually : 

https://github.com/alm-tools/alm/blob/f7cb04cb4f7819a7f6a0bca71b72c8ab5a8bd7ab/src/server/workers/external/gitService.ts#L135-L136

Thanks :rose:

**Comment by hoegge** [comment] 2017-07-28 11:08
By running these I assume the add and commit highlighted in the source? The add and commit runs fine from command line:
```
c:\Users\mhpedersen\Dropbox\Development\client MHP>git add -A

c:\Users\mhpedersen\Dropbox\Development\client MHP>git commit --message gittest
[master 45ff5c6] gittest
 11 files changed, 109 insertions(+), 258 deletions(-)

c:\Users\mhpedersen\Dropbox\Development\client MHP>
```

It seems like the error comes from the push part, which should not be run (I think) when there is no remote repository, or? Shouldn't push only be run if the user wishes to do so?

```
c:\Users\mhpedersen\Dropbox\Development\client MHP>git push origin HEAD
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by basarat** [comment] 2017-07-31 05:11
The command is `Git add all, commit and push` and that is what it will try to do 
https://alm-tools.gitbooks.io/alm/content/features/git.html#git-add-all-commit-and-push

Don't have a command `add, commit`. So closing. Sorry for any confusion :rose:

**Comment by hoegge** [comment] 2017-07-31 06:47
Well, shouldn't the gutter color bars show anyways? The add and commit succeed and the repository is updated. I assume the editor compares to the (local) repository and not the remote non-existing?

**Comment by basarat** [comment] 2017-07-31 07:48
Is the file commited? Non git commuted files will not show gutter colours.

**Comment by hoegge** [comment] 2017-07-31 12:58
Yes. The committee goes fine. It is just the push part that fails (since there is nowhere to push - why I think a add and commit without push would make a lot of sense too). Also when I commit from the command do line to git the colors should show up, right?

Morten H Pedersen
hoegge@gmail.com
+45 3054 5892

**Comment by basarat** [comment] 2017-07-31 22:22
> Well, shouldn't the gutter color bars show anyways

They will show if `git` works. Can you run the command manually and share the output : https://github.com/alm-tools/alm/blob/d9267c8e5a2e5f3ccd64c0c8954be808904df379/src/server/workers/external/gitService.ts#L83 :rose:

**Comment by hoegge** [comment] 2017-08-02 10:14
yes, files they are committed and git does not have problems with the command

```git diff -U0 --no-color --no-ext-diff HEAD ```

gives:

```diff --git a/webHost/system/Animator.ts b/webHost/system/Animator.ts
index f2a132e..b0468ea 100644
--- a/webHost/system/Animator.ts
+++ b/webHost/system/Animator.ts
@@ -306 +306 @@ namespace xfw_host_1_0_0 {
-                return Animator_Manual.Create(30);
+                return Animator_Manual.Create(30);  // mhp: does it work? Animator_Manual.Create returns and Animator_Base
diff --git a/webHost/visual/animation/Animator.ts b/webHost/visual/animation/Animator.ts
index 323430c..c9bbc11 100644
--- a/webHost/visual/animation/Animator.ts
+++ b/webHost/visual/animation/Animator.ts
@@ -2,52 +2,106 @@
-  export module visual {
-
-    import cor = xfw_core_1_0_0;
-    import col = cor.collections;
-    import obs = cor.observer;
-
-    import ver = xfw_host_1_0_0;
-    import geo = ver.geometry;
...
```

**Comment by hoegge** [comment] 2017-08-07 15:08
Did you get the info you needed?

**Comment by basarat** [comment] 2017-08-08 06:39
I use it on windows everyday. The fix would need to belong here : https://github.com/alm-tools/alm/blob/d9267c8e5a2e5f3ccd64c0c8954be808904df379/src/server/workers/external/gitService.ts#L84 but since I can't reproduce it, it will have to come from you :(. 

That said, reason why I'm not tackling it is suspected git or PATH malfunction on your machine.

**Comment by hoegge** [comment] 2017-08-08 11:26
Ok, ran some manual debugging adding some logs getting: 
```MHP: ###################################
MHP: just before calling gitCmd
MHP: c:/Users/mhpedersen/Dropbox/Development/client MHP/webShell/webShell.ts
MHP: Inside gitCmd with arguments: diff,-U0,--no-color,--no-ext-diff,HEAD,c:/Users/mhpedersen/Dropbox/Development/client MHP/webShell/webShell.ts
MHP Now inside passed function called on result by gitCMD -------------------------
MHP Calling res.match() with res being: fatal: Invalid object name 'c'.

and gitDiffRegex: /@@[^@@]*@@/g
MHP matches result: null
MHP: No matches -------------------------
MHP: exiting ################################
```
So the result of the git run is not too god. The command called by the `cp.exec` in `gitService.js` is:
```
git diff -U0 --no-color --no-ext-diff HEAD c:/Users/mhpedersen/Dropbox/Development/client MHP/webShell/webShell.ts
```
which gives the error that is the issue:

`fatal: Invalid object name 'c'.`

which is because the filename needs quotes like this: 
```
git diff -U0 --no-color --no-ext-diff HEAD "c:/Users/mhpedersen/Dropbox/Development/client MHP/webShell/webShell.ts"
```
which gives a good result:
```
diff --git a/webShell/webShell.ts b/webShell/webShell.ts
index a82afa7..e2c2246 100644
--- a/webShell/webShell.ts
+++ b/webShell/webShell.ts
@@ -1,0 +2,2 @@
+/// <reference path="shell/shelldesktop.ts" />
+// mhp: added line above to get shell to resolve
@@ -4,0 +7,2 @@
+// mhp: todo above: re-write to ES6 external modules instead of references
+//
@@ -15,2 +19,2 @@ namespace xfw_shell_1_0_0 {
-        let gStation: host.system.Station; // mhp: g_... why?
-        let gOverlay : host.diagnostics.Overlay;    // mhp: unused
+        let gStation: host.system.Station; // mhp: g_... why? Why initialized outside function - any need for that - any special reason?
+        // let gOverlay: host.diagnostics.Overlay;    // mhp: unused
@@ -26 +30 @@ namespace xfw_shell_1_0_0 {
-        // mhp: These things below actually run at load, because they are not assigned but just part of namespace
+
@@ -42,0 +47 @@ namespace xfw_shell_1_0_0 {
+            // mhp: why doesn't Initialize create an animator itself - does it ever not need one?
@@ -58,0 +64 @@ namespace xfw_shell_1_0_0 {
+// sfsdfjlkj
```

It probably runs fine on your system, because you don't have space ` ` in your file or path names?

I added the following `'"'` to the call:
`return gitCmd('diff', '-U0', '--no-color', '--no-ext-diff', 'HEAD', '"'+args.filePath+'"').then(function (res) {`
around the args.filePath and then I got the color bars! 
![screenshot029](https://user-images.githubusercontent.com/15846310/29069868-02670d78-7c3d-11e7-8bfa-009ba042faf5.png)

**Comment by hoegge** [comment] 2017-08-08 11:52
Another thing, maybe. It seems like the git diff command is called three times whenever you open a file. Isn't that a bug?

**Comment by basarat** [comment] 2017-08-09 00:49
> Another thing, maybe. It seems like the git diff command is called three times whenever you open a file. Isn't that a bug?

Fixed in attached commit ^ :rose:

**Comment by basarat** [comment] 2017-08-09 00:53
@hoegge Released with `2.37.3` :heart:

**Closed** 2017-08-09 00:52 UTC
Labels: status:more-info-needed

**Comment by hoegge** [comment] 2017-08-10 11:05
Nice! Thanks. Is there a difference between child_process.spawn and .exec in terms of handling spaces in path names? (since it seems to work fine with spawn without quotes in your implementation in gitCmdBetter)

**Comment by basarat** [comment] 2017-08-11 00:39
> Is there a difference between child_process.spawn and .exec in terms of handling spaces in path names

Yes :rose:
